const lowerBody = [
  'Back Squat',
  'Goblet Squat',
  'Deadlift',
  'Single Leg Squat',
  'Lunge',
  'RDL',
  'Single Leg Squat',
  'Single Leg Deadlift',
  'Snatch Grip Deadlift',
  'Kettlebell Deadlift',
  'Single Leg RDL',
  'Cossack Squat',
  'Front Squat',
];
const pull = [
  'Pull Up',
  'Crossover Row',
  'Australian Pull Up',
  'Chin Up',
  'Wide Grip Pull Up',
  'Bent Over Row',
];
const push = ['Overhead Press', 'Dip', 'Bench Press', 'Push Up', 'Two Hand Overhead Press'];
const warmup = [
  'Dowel Up and Over',
  'Deadlift Pattern',
  'Single Leg Deadlift Pattern',
  'Hip Thruster',
  '90-90',
  'Band Squat',
  'Crossover Warmup',
  'Plank Taps',
  'Reverse Hyperextension',
  'Side Plank',
  'Ass to Heals',
  'Curl Up',
];
const finisher = [
  'Mule Curl Up',
  'Reverse Hyperextension',
  'Pallof Press',
  'Carries',
  'Monster Walk',
  'Toes to Bar',
];

const movement = ['push', 'pull', 'lower body'];
const strengthRepsArray = [3, 4, 5, 6];
const hypertrophyRepsArray = [7, 8, 9, 10, 11, 12];
const enduranceRepsArray = [13, 14, 15, 16, 17, 18, 19, 20];
const repsArray = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
// make workouts array of objects

const resistanceTypeArray = [
  'lbs',
  'kgs',
  'loop band assistance',
  'loop band resistance',
  'crossover cords',
  'hip bands',
];
const lbsArray = Array.from(Array.from(Array(Math.ceil(500 - 0)).keys()), (x) => 0 + x);
const kgsArray = Array.from(Array.from(Array(Math.ceil((200 - 0) / 2)).keys()), (x) => 0 + x * 2);
// need to figure out assistance or resistance ... going to assume assistance with loops
const loopBandAssistanceArray = ['green', 'purple', 'black', 'red'];
const loopBandResistanceArray = ['red', 'black', 'purple', 'green'];
const crossOverCordsArray = ['purple', 'red', 'blue', 'orange'];
const hipBandArray = ['yellow', 'red', 'blue'];
const workouts = [
  {
    day: '1',
    warmup: [
      'warmup',
      {
        exerciseName: 'Dowel Over Under',
        set: 1,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Single Leg Deadlift Pattern',
        set: 1,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: null,
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Crossover Warmup',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'purple',
        resistanceType: 'Crossover Cords',
        workTime: 90,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Band Squat',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'red',
        resistanceType: 'hip bands',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Plank Tap',
        set: 3,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },

      {
        exerciseName: '90-90',
        set: 3,
        sets: 3,
        numReps: 5,
        resistance: 0,
        resistanceType: null,
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Side Plank',
        set: 4,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 20,
        restTime: 10,
        complete: false,
      },
      {
        exerciseName: 'Curl Up',
        set: 5,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 15,
        restTime: 5,
        complete: false,
      },
    ],
    strength: [
      'lower body',
      {
        exerciseName: 'Back Squat',
        set: 6,
        sets: 3,
        numReps: 3,
        resistance: 115,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
      {
        exerciseName: 'Single Leg Deadlift',
        set: 7,
        sets: 3,
        numReps: 5,
        resistance: 32,
        resistanceType: 'kgs',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
    ],
    hypertrophy: [
      'pull',
      {
        exerciseName: 'Pull Up',
        set: 6,
        sets: 3,
        numReps: 7,
        resistance: 'purple',
        resistanceType: 'loop band assistance',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Australian Pull Up',
        set: 8,
        sets: 3,
        numReps: 7,
        resistance: null,
        resistanceType: 'loop band resistance',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
    ],
    endurance: [
      'push',
      {
        exerciseName: 'Push Up',
        set: 7,
        sets: 3,
        numReps: 14,
        resistance: 0,
        resistanceType: 'loop band assistance',
        workTime: 45,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Overhead Press',
        set: 8,
        sets: 3,
        numReps: 14,
        resistance: 16,
        resistanceType: 'kgs',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
    finisher: [
      'finisher',
      {
        exerciseName: 'Toes to Bar',
        set: 9,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Monster Walk',
        set: 9,
        sets: 3,
        numReps: 14,
        resistance: 'red',
        resistanceType: 'hip bands',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
  },
  {
    day: '2',
    warmup: [
      'warmup',
      {
        exerciseName: 'Dowel Over Under',
        set: 1,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Deadlift Pattern',
        set: 1,
        sets: 3,
        numReps: 20,
        resistance: 0,
        resistanceType: null,
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Crossover Warmup',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'purple',
        resistanceType: 'Crossover Cords',
        workTime: 90,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Reverse Hyper',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'purple',
        resistanceType: 'loop band resistance',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Plank Tap',
        set: 3,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },

      {
        exerciseName: 'Ass to Heals',
        set: 3,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: 'lbs',
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Side Plank',
        set: 4,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 20,
        restTime: 10,
        complete: false,
      },
      {
        exerciseName: 'Curl Up',
        set: 5,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 15,
        restTime: 15,
        complete: false,
      },
    ],
    strength: [
      'push',
      {
        exerciseName: 'Bench Press',
        set: 6,
        sets: 3,
        numReps: 5,
        resistance: 95,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
      {
        exerciseName: 'Dip',
        set: 7,
        sets: 3,
        numReps: 5,
        resistance: 6,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
    ],
    hypertrophy: [
      'lower body',
      {
        exerciseName: 'Deadlift',
        set: 6,
        sets: 3,
        numReps: 7,
        resistance: 115,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Single Leg Squat',
        set: 8,
        sets: 3,
        numReps: 7,
        resistance: 0,
        resistanceType: 'lbs',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
    endurance: [
      'pull',
      {
        exerciseName: 'Chin Up',
        set: 7,
        sets: 3,
        numReps: 14,
        resistance: 'green',
        resistanceType: 'loop band assistance',
        workTime: 45,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Bent Over Row',
        set: 8,
        sets: 3,
        numReps: 14,
        resistance: 16,
        resistanceType: 'kgs',
        workTime: 45,
        restTime: 30,
        complete: false,
      },
    ],
    finisher: [
      'finisher',
      {
        exerciseName: 'Pallof Press',
        set: 9,
        sets: 3,
        numReps: 10,
        resistance: 'red',
        resistanceType: 'crossover cords',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Monster Walk',
        set: 9,
        sets: 3,
        numReps: 14,
        resistance: 'blue',
        resistanceType: 'hip bands',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
  },
  {
    day: '3',
    warmup: [
      'warmup',
      {
        exerciseName: 'Dowel Over Under',
        set: 1,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Single Leg Deadlift Pattern',
        set: 1,
        sets: 3,
        numReps: 20,
        resistance: 0,
        resistanceType: null,
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Crossover Warmup',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'purple',
        resistanceType: 'Crossover Cords',
        workTime: 90,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Band Squat',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'purple',
        resistanceType: 'loop band resistance',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Plank Tap',
        set: 3,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },

      {
        exerciseName: '90-90',
        set: 3,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: 'lbs',
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Side Plank',
        set: 4,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 20,
        restTime: 10,
        complete: false,
      },
      {
        exerciseName: 'Curl Up',
        set: 5,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 15,
        restTime: 15,
        complete: false,
      },
    ],
    strength: [
      'pull',
      {
        exerciseName: 'Wide Grip Pull Up',
        set: 6,
        sets: 3,
        numReps: 5,
        resistance: 'green',
        resistanceType: 'loop band assistance',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
      {
        exerciseName: 'Australian Pull Up',
        set: 7,
        sets: 3,
        numReps: 5,
        resistance: 0,
        resistanceType: 'loop band resistance',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
    ],
    hypertrophy: [
      'push',
      {
        exerciseName: 'Push Up',
        set: 6,
        sets: 3,
        numReps: 7,
        resistance: 'black',
        resistanceType: 'loop band resistance',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Two Hand Overhead Press',
        set: 8,
        sets: 3,
        numReps: 7,
        resistance: 32,
        resistanceType: 'kgs',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
    endurance: [
      'lower body',
      {
        exerciseName: 'Goblet Squat',
        set: 7,
        sets: 3,
        numReps: 14,
        resistance: 16,
        resistanceType: 'kgs',
        workTime: 45,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Single Leg RDL',
        set: 8,
        sets: 3,
        numReps: 14,
        resistance: 32,
        resistanceType: 'kgs',
        workTime: 45,
        restTime: 30,
        complete: false,
      },
    ],
    finisher: [
      'finisher',
      {
        exerciseName: 'Carries',
        set: 9,
        sets: 5,
        numReps: 1,
        resistance: 32,
        resistanceType: 'kgs',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Monster Walk',
        set: 9,
        sets: 3,
        numReps: 1,
        resistance: 'red',
        resistanceType: 'hip bands',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
  },
  {
    day: '4',
    warmup: [
      'warmup',
      {
        exerciseName: 'Dowel Over Under',
        set: 1,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Deadlift Pattern',
        set: 1,
        sets: 3,
        numReps: 20,
        resistance: 0,
        resistanceType: null,
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Crossover Warmup',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'purple',
        resistanceType: 'Crossover Cords',
        workTime: 90,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Hip Thruster',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 65,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Plank Tap',
        set: 3,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },

      {
        exerciseName: 'Ass to Heals',
        set: 3,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: 'lbs',
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Side Plank',
        set: 4,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 20,
        restTime: 10,
        complete: false,
      },
      {
        exerciseName: 'Curl Up',
        set: 5,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 15,
        restTime: 15,
        complete: false,
      },
    ],
    strength: [
      'lower body',
      {
        exerciseName: 'Snatch Grip Deadlift',
        set: 6,
        sets: 3,
        numReps: 5,
        resistance: 95,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
      {
        exerciseName: 'Single Leg Squat',
        set: 7,
        sets: 3,
        numReps: 5,
        resistance: 12,
        resistanceType: 'kgs',
        workTime: 60,
        restTime: 60,
        complete: false,
      },
    ],
    hypertrophy: [
      'pull',
      {
        exerciseName: 'Pull Up',
        set: 6,
        sets: 3,
        numReps: 7,
        resistance: 'purple',
        resistanceType: 'loop band assistance',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Bent Over Row',
        set: 8,
        sets: 3,
        numReps: 7,
        resistance: 20,
        resistanceType: 'kgs',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
    endurance: [
      'push',
      {
        exerciseName: 'Push Up',
        set: 7,
        sets: 3,
        numReps: 14,
        resistance: 16,
        resistanceType: 'kgs',
        workTime: 45,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Dip',
        set: 8,
        sets: 3,
        numReps: 14,
        resistance: 'purple',
        resistanceType: 'loop band assistance',
        workTime: 45,
        restTime: 30,
        complete: false,
      },
    ],
    finisher: [
      'finisher',
      {
        exerciseName: 'Mule Curl Up',
        set: 9,
        sets: 3,
        numReps: 15,
        resistance: 0,
        resistanceType: 'lbs',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Reverse Hyperextension',
        set: 9,
        sets: 3,
        numReps: 10,
        resistance: 16,
        resistanceType: 'lbs',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
  },
  {
    day: '5',
    warmup: [
      'warmup',
      {
        exerciseName: 'Dowel Over Under',
        set: 1,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Deadlift Pattern',
        set: 1,
        sets: 3,
        numReps: 20,
        resistance: 0,
        resistanceType: null,
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Crossover Warmup',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'purple',
        resistanceType: 'Crossover Cords',
        workTime: 90,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Band Squat',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'red',
        resistanceType: 'hip bands',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Plank Tap',
        set: 3,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },

      {
        exerciseName: '90-90',
        set: 3,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: 'lbs',
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Side Plank',
        set: 4,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 20,
        restTime: 10,
        complete: false,
      },
      {
        exerciseName: 'Curl Up',
        set: 5,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 15,
        restTime: 15,
        complete: false,
      },
    ],
    strength: [
      'push',
      {
        exerciseName: 'Bench Press',
        set: 6,
        sets: 3,
        numReps: 5,
        resistance: 95,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
      {
        exerciseName: 'Overhead Press',
        set: 7,
        sets: 3,
        numReps: 5,
        resistance: 24,
        resistanceType: 'kgs',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
    ],
    hypertrophy: [
      'lower body',
      {
        exerciseName: 'Front Squat',
        set: 6,
        sets: 3,
        numReps: 7,
        resistance: 75,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Cossack Squat',
        set: 8,
        sets: 3,
        numReps: 7,
        resistance: 0,
        resistanceType: 'kgs',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
    endurance: [
      'pull',
      {
        exerciseName: 'Chin Up',
        set: 7,
        sets: 3,
        numReps: 14,
        resistance: 'green',
        resistanceType: 'loop band assistance',
        workTime: 45,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Australian Pull Up',
        set: 8,
        sets: 3,
        numReps: 14,
        resistance: 0,
        resistanceType: 'loop band resistance',
        workTime: 45,
        restTime: 30,
        complete: false,
      },
    ],
    finisher: [
      'finisher',
      {
        exerciseName: 'Toes to Bar',
        set: 9,
        sets: 5,
        numReps: 20,
        resistance: 0,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Monster Walk',
        set: 9,
        sets: 3,
        numReps: 1,
        resistance: 'red',
        resistanceType: 'hip bands',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
  },
  {
    day: '6',
    warmup: [
      'warmup',
      {
        exerciseName: 'Dowel Over Under',
        set: 1,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Deadlift Pattern',
        set: 1,
        sets: 3,
        numReps: 20,
        resistance: 0,
        resistanceType: null,
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Crossover Warmup',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'purple',
        resistanceType: 'Crossover Cords',
        workTime: 90,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Reverse Hyperextension',
        set: 2,
        sets: 3,
        numReps: 10,
        resistance: 'purple',
        resistanceType: 'loop band resistance',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Plank Tap',
        set: 3,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 30,
        restTime: 5,
        complete: false,
      },

      {
        exerciseName: 'Ass to Heals',
        set: 3,
        sets: 3,
        numReps: 10,
        resistance: 0,
        resistanceType: 'lbs',
        workTime: 60,
        restTime: 5,
        complete: false,
      },
      {
        exerciseName: 'Side Plank',
        set: 4,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 20,
        restTime: 10,
        complete: false,
      },
      {
        exerciseName: 'Curl Up',
        set: 5,
        sets: 3,
        numReps: 0,
        resistance: 0,
        resistanceType: null,
        workTime: 15,
        restTime: 15,
        complete: false,
      },
    ],
    strength: [
      'pull',
      {
        exerciseName: 'Wide Grip Pull Up',
        set: 6,
        sets: 3,
        numReps: 5,
        resistance: 'purple',
        resistanceType: 'loop band assistance',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
      {
        exerciseName: 'Bent Over Row',
        set: 7,
        sets: 3,
        numReps: 5,
        resistance: 24,
        resistanceType: 'kgs',
        workTime: 30,
        restTime: 60,
        complete: false,
      },
    ],
    hypertrophy: [
      'push',
      {
        exerciseName: 'Push Up',
        set: 6,
        sets: 3,
        numReps: 7,
        resistance: 'black',
        resistanceType: 'loop band resistance',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Dip',
        set: 8,
        sets: 3,
        numReps: 7,
        resistance: 4,
        resistanceType: 'lbs',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
    endurance: [
      'lower body',
      {
        exerciseName: 'Kettlebell Deadlift',
        set: 7,
        sets: 3,
        numReps: 14,
        resistance: 32,
        resistanceType: 'kgs',
        workTime: 45,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Lunge',
        set: 8,
        sets: 3,
        numReps: 14,
        resistance: 16,
        resistanceType: 'kgs',
        workTime: 60,
        restTime: 30,
        complete: false,
      },
    ],
    finisher: [
      'finisher',
      {
        exerciseName: 'Mule Curl Up',
        set: 9,
        sets: 5,
        numReps: 20,
        resistance: 0,
        resistanceType: 'lbs',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
      {
        exerciseName: 'Reverse Hyperextension',
        set: 9,
        sets: 3,
        numReps: 10,
        resistance: 'red',
        resistanceType: 'loop band resistance',
        workTime: 30,
        restTime: 30,
        complete: false,
      },
    ],
  },
];

const arraySelect = (str, exerciseName) => {
  if (str === 'push') {
    return push;
  }
  if (str === 'pull') {
    return pull;
  }
  if (str === 'lower body') {
    return lowerBody;
  }
  if (str === 'warmup') {
    return warmup;
  }
  if (str === 'finisher') {
    return finisher;
  }
  if (str === 'lbs') {
    return lbsArray;
  }
  if (str === 'kgs') {
    return kgsArray;
  }
  if (str === 'loop band assistance') {
    return loopBandAssistanceArray;
  }

  if (str === 'loop band resistance') {
    return loopBandResistanceArray;
  }
  if (str === 'crossover cords') {
    return crossOverCordsArray;
  }
  if (str === 'hip bands') {
    return hipBandArray;
  }
  if (str === null) {
    return [null, null, null, ''];
  }
  return str;
};
export {
  lowerBody,
  warmup,
  push,
  pull,
  finisher,
  movement,
  hypertrophyRepsArray,
  strengthRepsArray,
  enduranceRepsArray,
  resistanceTypeArray,
  lbsArray,
  kgsArray,
  loopBandAssistanceArray,
  loopBandResistanceArray,
  crossOverCordsArray,
  hipBandArray,
  workouts,
  arraySelect,
  repsArray,
};
