export const squatWarmup = [
  {
    exerciseName: 'Dowel Over Under',
    groupNumber: 1,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'shoulderMobility',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Deadlift Pattern',
    groupNumber: 1,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'movementPattern',
    exerciseIntensity: 'warmup',
    workTime: 60,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Crossover Warmup',
    groupNumber: 2,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 'purple',
    resistanceType: 'crossover cords',
    exerciseType: 'shoulderStability',
    exerciseIntensity: 'warmup',
    workTime: 90,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Band Squat',
    groupNumber: 2,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 'red',
    resistanceType: 'hip bands',
    exerciseType: 'hipStability',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Plank Taps',
    groupNumber: 3,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 5,
    complete: false,
  },

  {
    exerciseName: '90-90',
    groupNumber: 3,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'hipStability',
    exerciseIntensity: 'warmup',
    workTime: 60,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Side Plank',
    groupNumber: 4,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 20,
    restTime: 10,
    complete: false,
  },
  {
    exerciseName: 'Curl Up',
    groupNumber: 5,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 15,
    restTime: 5,
    complete: false,
  },
];
const deadliftWarmup = [
  {
    exerciseName: 'Dowel Over Under',
    groupNumber: 1,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'shoulderMobility',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Deadlift Pattern',
    groupNumber: 1,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'movementPattern',
    exerciseIntensity: 'warmup',
    workTime: 60,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Crossover Warmup',
    groupNumber: 2,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 'purple',
    resistanceType: 'crossover cords',
    exerciseType: 'shoulderStability',
    exerciseIntensity: 'warmup',
    workTime: 90,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Reverse Hyper',
    groupNumber: 2,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 'purple',
    resistanceType: 'loop band resistance',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Plank Taps',
    groupNumber: 3,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 5,
    complete: false,
  },

  {
    exerciseName: 'Ass to Heals',
    groupNumber: 3,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 60,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Side Plank',
    groupNumber: 4,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 20,
    restTime: 10,
    complete: false,
  },
  {
    exerciseName: 'Curl Up',
    groupNumber: 5,
    totalSets: 3,
    numReps: 1,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 15,
    restTime: 15,
    complete: false,
  },
];

const tTBAndThrusterFinisher = [
  {
    exerciseName: 'Toes to Bar',
    groupNumber: 9,
    totalSets: 3,
    numReps: 12,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'finisher',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Hip Thruster',
    groupNumber: 9,
    totalSets: 3,
    numReps: 12,
    setsCompleted: 0,
    resistance: 65,
    exerciseType: 'hipStability',
    resistanceType: 'lbs',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

export const progressedTTBAndThrusterFinisher = [
  {
    exerciseName: 'Toes to Bar',
    groupNumber: 9,
    totalSets: 3,
    numReps: 13,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'finisher',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Hip Thruster',
    groupNumber: 9,
    totalSets: 3,
    numReps: 13,
    setsCompleted: 0,
    resistance: 65,
    exerciseType: 'hipStability',
    resistanceType: 'lbs',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

const pallofAndMonsterFinisher = [
  {
    exerciseName: 'Pallof Press',
    groupNumber: 9,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 'red',
    resistanceType: 'crossover cords',
    exerciseType: 'coreStability',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Monster Walk',
    groupNumber: 9,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 'blue',
    resistanceType: 'hip bands',
    exerciseType: 'hipStability',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

const muleFinisher = [
  {
    exerciseName: 'Mule Curl Up',
    groupNumber: 9,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Reverse Hyper',
    groupNumber: 9,
    totalSets: 3,
    numReps: 10,
    setsCompleted: 0,
    resistance: 16,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

const workout1 = [
  {
    exerciseName: 'Back Squat',
    groupNumber: 6,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 115,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Pull Up',
    groupNumber: 6,
    totalSets: 3,
    numReps: 8,
    setsCompleted: 0,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Deadlift',
    groupNumber: 7,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Push Up',
    groupNumber: 7,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'loop band resistance',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Australian Pull Up',
    groupNumber: 8,
    totalSets: 3,
    numReps: 8,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'loop band resistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Overhead Press',
    groupNumber: 8,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 16,
    resistanceType: 'kgs',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

const workout2 = [
  {
    exerciseName: 'Bench Press',
    groupNumber: 6,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 95,
    resistanceType: 'lbs',
    exerciseType: 'push',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Deadlift',
    groupNumber: 6,
    totalSets: 3,
    numReps: 8,
    setsCompleted: 0,
    resistance: 115,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Dip',
    groupNumber: 7,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 5,
    resistanceType: 'lbs',
    exerciseType: 'push',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Chin Up',
    groupNumber: 7,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 'green',
    exerciseType: 'pull',
    resistanceType: 'loop band assistance',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Squat',
    groupNumber: 8,
    totalSets: 3,
    numReps: 8,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'hypertrophy',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Bent Over Row',
    groupNumber: 8,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 24,
    resistanceType: 'kgs',
    exerciseType: 'pull',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
];
const workout3 = [
  {
    exerciseName: 'Wide Grip Pull Up',
    groupNumber: 6,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 'green',
    exerciseType: 'pull',
    resistanceType: 'loop band assistance',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Push Up',
    groupNumber: 6,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 'black',
    resistanceType: 'loop band resistance',
    exerciseType: 'push',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Australian Pull Up',
    groupNumber: 7,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'loop band resistance',
    exerciseType: 'pull',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Goblet Squat',
    groupNumber: 7,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 16,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Two Hand Overhead Press',
    groupNumber: 8,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseIntensity: 'hypertrophy',
    exerciseType: 'push',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg RDL',
    groupNumber: 8,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
];

const workout4 = [
  {
    exerciseName: 'Snatch Grip Deadlift',
    groupNumber: 6,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 95,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Pull Up',
    groupNumber: 6,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Squat',
    groupNumber: 7,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 12,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 60,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Push Up',
    groupNumber: 7,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 16,
    resistanceType: 'kgs',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Bent Over Row',
    groupNumber: 8,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 20,
    resistanceType: 'kgs',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Dip',
    groupNumber: 8,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
];

const workout5 = [
  {
    exerciseName: 'Bench Press',
    groupNumber: 6,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 95,
    resistanceType: 'lbs',
    exerciseType: 'push',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Front Squat',
    groupNumber: 6,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 75,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Overhead Press',
    groupNumber: 7,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 24,
    resistanceType: 'kgs',
    exerciseType: 'push',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Chin Up',
    groupNumber: 7,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 'green',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Cossack Squat',
    groupNumber: 8,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'hypertrophy',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Australian Pull Up',
    groupNumber: 8,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'loop band resistance',
    exerciseType: 'pull',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
];

const workout6 = [
  {
    exerciseName: 'Wide Grip Pull Up',
    groupNumber: 6,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Push Up',
    groupNumber: 6,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 'black',
    resistanceType: 'loop band resistance',
    exerciseType: 'push',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Bent Over Row',
    groupNumber: 7,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 24,
    resistanceType: 'kgs',
    exerciseIntensity: 'strength',
    exerciseType: 'pull',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Kettlebell Deadlift',
    groupNumber: 7,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Dip',
    groupNumber: 8,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 5,
    resistanceType: 'lbs',
    exerciseType: 'push',
    exerciseIntensity: 'hypertrophy',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Lunge',
    groupNumber: 8,
    totalSets: 3,
    numReps: 14,
    setsCompleted: 0,
    resistance: 16,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'endurance',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

const progressedCoreSquatExerciseList = [
  {
    exerciseName: 'Back Squat',
    groupNumber: 6,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 120,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Pull Up',
    groupNumber: 6,
    totalSets: 3,
    numReps: 9,
    setsCompleted: 0,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Deadlift',
    groupNumber: 7,
    totalSets: 3,
    numReps: 6,
    setsCompleted: 0,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Push Up',
    groupNumber: 7,
    totalSets: 3,
    numReps: 12,
    setsCompleted: 0,
    resistance: 'red',
    resistanceType: 'loop band resistance',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Australian Pull Up',
    groupNumber: 8,
    totalSets: 3,
    numReps: 9,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'loop band resistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Overhead Press',
    groupNumber: 8,
    totalSets: 3,
    numReps: 12,
    setsCompleted: 0,
    resistance: 20,
    resistanceType: 'kgs',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

export const unprogressedLoopBandExercise = {
  exerciseName: 'Push Up',
  groupNumber: 7,
  totalSets: 3,
  numReps: 14,
  setsCompleted: 0,
  resistance: 0,
  resistanceType: 'loop band resistance',
  exerciseType: 'push',
  exerciseIntensity: 'endurance',
  workTime: 45,
  restTime: 30,
  complete: false,
};

export const progressedLoopBandExercise = {
  exerciseName: 'Push Up',
  groupNumber: 7,
  totalSets: 3,
  numReps: 12,
  setsCompleted: 0,
  resistance: 'red',
  resistanceType: 'loop band resistance',
  exerciseType: 'push',
  exerciseIntensity: 'endurance',
  workTime: 45,
  restTime: 30,
  complete: false,
};

export const partiallyProgressedCoreSquatExerciseList = [
  {
    exerciseName: 'Back Squat',
    groupNumber: 6,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 115,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Pull Up',
    groupNumber: 6,
    totalSets: 3,
    numReps: 8,
    setsCompleted: 0,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Deadlift',
    groupNumber: 7,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Push Up',
    groupNumber: 7,
    totalSets: 3,
    numReps: 12,
    setsCompleted: 0,
    resistance: 'red',
    resistanceType: 'loop band resistance',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Australian Pull Up',
    groupNumber: 8,
    totalSets: 3,
    numReps: 9,
    setsCompleted: 0,
    resistance: 0,
    resistanceType: 'loop band resistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Overhead Press',
    groupNumber: 8,
    totalSets: 3,
    numReps: 12,
    setsCompleted: 0,
    resistance: 20,
    resistanceType: 'kgs',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

export const unprogressedCoreSquatExercises = [
  {
    exerciseName: 'Back Squat',
    groupNumber: 6,
    totalSets: 3,
    numReps: 7,
    setsCompleted: 0,
    resistance: 115,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Pull Up',
    groupNumber: 6,
    totalSets: 3,
    numReps: 8,
    setsCompleted: 0,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Deadlift',
    groupNumber: 7,
    totalSets: 3,
    numReps: 5,
    setsCompleted: 0,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
];
export const fullSquatExerciseList = squatWarmup.concat(workout1, tTBAndThrusterFinisher);
export const fullDeadLiftExerciseList = deadliftWarmup.concat(workout2, pallofAndMonsterFinisher);
export const progressedSquatExerciseList = squatWarmup.concat(
  progressedCoreSquatExerciseList,
  progressedTTBAndThrusterFinisher,
);
export const partiallyProgressedSquatExercises = squatWarmup.concat(
  partiallyProgressedCoreSquatExerciseList,
  progressedTTBAndThrusterFinisher,
);

export const unprogressedSquatExercises = squatWarmup.concat(unprogressedCoreSquatExercises);
/*
const fullWorkout3 = squatWarmup.concat(workout3, muleFinisher);
const fullWorkout4 = deadliftWarmup.concat(workout4, tTBAndThrusterFinisher);
const fullWorkout5 = squatWarmup.concat(workout5, pallofAndMonsterFinisher);
const fullWorkout6 = deadliftWarmup.concat(workout6, muleFinisher);
*/
export const trainingSessions = [
  fullSquatExerciseList,
  fullDeadLiftExerciseList,
  /*
  fullWorkout3,
  fullWorkout4,
  fullWorkout5,
  fullWorkout6,
  */
];
