const squatWarmup = [
  {
    exerciseName: 'Dowel Over Under',
    set: 1,
    sets: 3,
    numReps: 10,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'shoulderMobility',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Deadlift Pattern',
    set: 1,
    sets: 3,
    numReps: 10,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'movementPattern',
    exerciseIntensity: 'warmup',
    workTime: 60,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Crossover Warmup',
    set: 2,
    sets: 3,
    numReps: 10,
    resistance: 'purple',
    resistanceType: 'crossover cords',
    exerciseType: 'shoulderStability',
    exerciseIntensity: 'warmup',
    workTime: 90,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Band Squat',
    set: 2,
    sets: 3,
    numReps: 10,
    resistance: 'red',
    resistanceType: 'hip bands',
    exerciseType: 'hipStability',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Plank Taps',
    set: 3,
    sets: 3,
    numReps: 1,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 5,
    complete: false,
  },

  {
    exerciseName: '90-90',
    set: 3,
    sets: 3,
    numReps: 5,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'hipStability',
    exerciseIntensity: 'warmup',
    workTime: 60,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Side Plank',
    set: 4,
    sets: 3,
    numReps: 1,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 20,
    restTime: 10,
    complete: false,
  },
  {
    exerciseName: 'Curl Up',
    set: 5,
    sets: 3,
    numReps: 1,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 15,
    restTime: 5,
    complete: false,
  },
];
const deadliftWarmup = [
  {
    exerciseName: 'Dowel Over Under',
    set: 1,
    sets: 3,
    numReps: 10,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'shoulderMobility',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Deadlift Pattern',
    set: 1,
    sets: 3,
    numReps: 20,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'movementPattern',
    exerciseIntensity: 'warmup',
    workTime: 60,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Crossover Warmup',
    set: 2,
    sets: 3,
    numReps: 10,
    resistance: 'purple',
    resistanceType: 'crossover cords',
    exerciseType: 'shoulderStability',
    exerciseIntensity: 'warmup',
    workTime: 90,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Reverse Hyper',
    set: 2,
    sets: 3,
    numReps: 10,
    resistance: 'purple',
    resistanceType: 'loop band resistance',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Plank Taps',
    set: 3,
    sets: 3,
    numReps: 1,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 30,
    restTime: 5,
    complete: false,
  },

  {
    exerciseName: 'Ass to Heals',
    set: 3,
    sets: 3,
    numReps: 10,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 60,
    restTime: 5,
    complete: false,
  },
  {
    exerciseName: 'Side Plank',
    set: 4,
    sets: 3,
    numReps: 1,
    resistance: 0,
    resistanceType: 'none',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 20,
    restTime: 10,
    complete: false,
  },
  {
    exerciseName: 'Curl Up',
    set: 5,
    sets: 3,
    numReps: 1,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'warmup',
    workTime: 15,
    restTime: 15,
    complete: false,
  },
];

const tTBAndThrusterFinisher = [
  {
    exerciseName: 'Toes to Bar',
    set: 9,
    sets: 3,
    numReps: 10,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'finisher',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Hip Thruster',
    set: 9,
    sets: 3,
    numReps: 10,
    resistance: 65,
    exerciseType: 'hipStability',
    resistanceType: 'lbs',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

const pallofAndMonsterFinisher = [
  {
    exerciseName: 'Pallof Press',
    set: 9,
    sets: 3,
    numReps: 10,
    resistance: 'red',
    resistanceType: 'crossover cords',
    exerciseType: 'coreStability',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Monster Walk',
    set: 9,
    sets: 3,
    numReps: 14,
    resistance: 'blue',
    resistanceType: 'hip bands',
    exerciseType: 'hipStability',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

const muleFinisher = [
  {
    exerciseName: 'Mule Curl Up',
    set: 9,
    sets: 3,
    numReps: 15,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Reverse Hyper',
    set: 9,
    sets: 3,
    numReps: 10,
    resistance: 16,
    resistanceType: 'lbs',
    exerciseType: 'coreStability',
    exerciseIntensity: 'finisher',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

const workout1 = [
  {
    exerciseName: 'Back Squat',
    set: 6,
    sets: 3,
    numReps: 3,
    resistance: 115,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Pull Up',
    set: 6,
    sets: 3,
    numReps: 7,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Deadlift',
    set: 7,
    sets: 3,
    numReps: 5,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Push Up',
    set: 7,
    sets: 3,
    numReps: 14,
    resistance: 0,
    resistanceType: 'loop band assistance',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Australian Pull Up',
    set: 8,
    sets: 3,
    numReps: 7,
    resistance: 0,
    resistanceType: 'loop band resistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Overhead Press',
    set: 8,
    sets: 3,
    numReps: 14,
    resistance: 16,
    resistanceType: 'kgs',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

const workout2 = [
  {
    exerciseName: 'Bench Press',
    set: 6,
    sets: 3,
    numReps: 5,
    resistance: 95,
    resistanceType: 'lbs',
    exerciseType: 'push',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Deadlift',
    set: 6,
    sets: 3,
    numReps: 7,
    resistance: 115,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Dip',
    set: 7,
    sets: 3,
    numReps: 5,
    resistance: 6,
    resistanceType: 'lbs',
    exerciseType: 'push',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Chin Up',
    set: 7,
    sets: 3,
    numReps: 14,
    resistance: 'green',
    exerciseType: 'pull',
    resistanceType: 'loop band assistance',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Squat',
    set: 8,
    sets: 3,
    numReps: 7,
    resistance: 0,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'hypertrophy',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Bent Over Row',
    set: 8,
    sets: 3,
    numReps: 14,
    resistance: 16,
    resistanceType: 'kgs',
    exerciseType: 'pull',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
];
const workout3 = [
  {
    exerciseName: 'Wide Grip Pull Up',
    set: 6,
    sets: 3,
    numReps: 5,
    resistance: 'green',
    exerciseType: 'pull',
    resistanceType: 'loop band assistance',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Push Up',
    set: 6,
    sets: 3,
    numReps: 7,
    resistance: 'black',
    resistanceType: 'loop band resistance',
    exerciseType: 'push',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Australian Pull Up',
    set: 7,
    sets: 3,
    numReps: 5,
    resistance: 0,
    resistanceType: 'loop band resistance',
    exerciseType: 'pull',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Goblet Squat',
    set: 7,
    sets: 3,
    numReps: 14,
    resistance: 16,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Two Hand Overhead Press',
    set: 8,
    sets: 3,
    numReps: 7,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseIntensity: 'hypertrophy',
    exerciseType: 'push',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg RDL',
    set: 8,
    sets: 3,
    numReps: 14,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
];

const workout4 = [
  {
    exerciseName: 'Snatch Grip Deadlift',
    set: 6,
    sets: 3,
    numReps: 5,
    resistance: 95,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Pull Up',
    set: 6,
    sets: 3,
    numReps: 7,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Single Leg Squat',
    set: 7,
    sets: 3,
    numReps: 5,
    resistance: 12,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'strength',
    workTime: 60,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Push Up',
    set: 7,
    sets: 3,
    numReps: 14,
    resistance: 16,
    resistanceType: 'kgs',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Bent Over Row',
    set: 8,
    sets: 3,
    numReps: 7,
    resistance: 20,
    resistanceType: 'kgs',
    exerciseType: 'pull',
    exerciseIntensity: 'hypertrophy',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Dip',
    set: 8,
    sets: 3,
    numReps: 14,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'push',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
];

const workout5 = [
  {
    exerciseName: 'Bench Press',
    set: 6,
    sets: 3,
    numReps: 5,
    resistance: 95,
    resistanceType: 'lbs',
    exerciseType: 'push',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Front Squat',
    set: 6,
    sets: 3,
    numReps: 7,
    resistance: 75,
    resistanceType: 'lbs',
    exerciseType: 'lower body',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Overhead Press',
    set: 7,
    sets: 3,
    numReps: 5,
    resistance: 24,
    resistanceType: 'kgs',
    exerciseType: 'push',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Chin Up',
    set: 7,
    sets: 3,
    numReps: 14,
    resistance: 'green',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Cossack Squat',
    set: 8,
    sets: 3,
    numReps: 7,
    resistance: 0,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'hypertrophy',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Australian Pull Up',
    set: 8,
    sets: 3,
    numReps: 14,
    resistance: 0,
    resistanceType: 'loop band resistance',
    exerciseType: 'pull',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
];

const workout6 = [
  {
    exerciseName: 'Wide Grip Pull Up',
    set: 6,
    sets: 3,
    numReps: 5,
    resistance: 'purple',
    resistanceType: 'loop band assistance',
    exerciseType: 'pull',
    exerciseIntensity: 'strength',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Push Up',
    set: 6,
    sets: 3,
    numReps: 7,
    resistance: 'black',
    resistanceType: 'loop band resistance',
    exerciseType: 'push',
    exerciseIntensity: 'hypertrophy',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Bent Over Row',
    set: 7,
    sets: 3,
    numReps: 5,
    resistance: 24,
    resistanceType: 'kgs',
    exerciseIntensity: 'strength',
    exerciseType: 'pull',
    workTime: 30,
    restTime: 60,
    complete: false,
  },
  {
    exerciseName: 'Kettlebell Deadlift',
    set: 7,
    sets: 3,
    numReps: 14,
    resistance: 32,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'endurance',
    workTime: 45,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Dip',
    set: 8,
    sets: 3,
    numReps: 7,
    resistance: 4,
    resistanceType: 'lbs',
    exerciseType: 'push',
    exerciseIntensity: 'hypertrophy',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
  {
    exerciseName: 'Lunge',
    set: 8,
    sets: 3,
    numReps: 14,
    resistance: 16,
    resistanceType: 'kgs',
    exerciseType: 'lower body',
    exerciseIntensity: 'endurance',
    workTime: 60,
    restTime: 30,
    complete: false,
  },
];

const fullWorkout1 = squatWarmup.concat(workout1, tTBAndThrusterFinisher);
const fullWorkout2 = deadliftWarmup.concat(workout2, pallofAndMonsterFinisher);
const fullWorkout3 = squatWarmup.concat(workout3, muleFinisher);
const fullWorkout4 = deadliftWarmup.concat(workout4, tTBAndThrusterFinisher);
const fullWorkout5 = squatWarmup.concat(workout5, pallofAndMonsterFinisher);
const fullWorkout6 = deadliftWarmup.concat(workout6, muleFinisher);

const workouts = [
  fullWorkout1,
  fullWorkout2,
  fullWorkout3,
  fullWorkout4,
  fullWorkout5,
  fullWorkout6,
];

export default workouts;
